version: "3.4"

services:
  hybrid.working.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7066;http://+:7065
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=Password@123"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
      - "ConnectionStrings__DefaultConnection=Server=hybrid.working.db;Database=HybridWorking;User=sa;Password=Password@123;MultipleActiveResultSets=true"
    ports:
      - "7065:7065"
      - "7066:7066"
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - hybrid.working.db
    restart: on-failure

  hybrid.working.db:
    environment:
      - MSSQL_SA_PASSWORD=Password@123
      - MSSQL_PID=Developer
      - ACCEPT_EULA=Y
    volumes:
      - ./volumes/data2:/var/opt/mssql/data
