version: '3.4'

services:
  hybrid.working.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7066;http://+:7065
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=Password123!"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
      - "ConnectionStrings__DefaultConnection=Server=hybrid.working.db;Database=HybridWorking;User=sa;Password=Password123!;MultipleActiveResultSets=true"
    ports:
      - "7065:7065"
      - "7066:7066"
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - hybrid.working.db
    restart: on-failure

  hybrid.working.db:
    ports:
      - "1433:1433"
    environment:
      - "SA_PASSWORD=Password123!"
      - "ACCEPT_EULA=Y" 